#!/bin/bash
#
# pi2s3:
#
#  afterBackup
# ===============
#
#

#
# Place the commands that should be run AFTER the backup here
#
#   $1 receives the status code. 0 = success / 2 = failure.
if [ $1 -ne 2 ]; then
    echo "Backup was ok"
else
    echo "Backup had an error"
fi
